version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      minor-e-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5
    target-branch: develop
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: weekly
    target-branch: develop
  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: weekly
    target-branch: develop
