packages:
  - apps/*
  - packages/*

allowBuilds:
  '@nestjs/core': true
  sharp: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
