#!/usr/bin/env python3
from pathlib import Path
import base64, re, math
ROOT=Path('/root/.openclaw/workspace')
SKILL=ROOT/'brains/time/areas/backoffice-suporte/skills/estudo-eficiencia-energetica'
TPL=SKILL/'templates/modelo-aprovado-cliente-serra-verde-2025-06-b.html'
LOGO=ROOT/'skills/relatorio-economia-plugga/assets/logo_clara.png'
OUT=ROOT/'reports/auditoria_energetica_jardim_floresta_uc_01374052_2026_06_client.html'
approved=TPL.read_text(encoding='utf-8')
style=re.search(r'<style>(.*?)</style>', approved, re.S).group(1)
# Preserve approved CSS; add only case-specific chart helpers without changing architecture.
style += '''\n.warn{border-left:5px solid #f59e0b;background:#fff8eb;padding:12px 14px;border-radius:10px;margin:10px 32px;color:#4b3412}.ok{border-left:5px solid var(--teal);background:#f7fbf9;padding:12px 14px;border-radius:10px;margin:10px 32px}.scenario-table td:nth-child(n+2){text-align:right}.scenario-table td:last-child{text-align:left}.flow-grid{display:grid;grid-template-columns:1.5fr 1fr;gap:16px;margin:16px 32px}.flow-grid .mini-chart{min-height:260px}@media print{.warn,.ok,.flow-grid{break-inside:avoid;page-break-inside:avoid}.flow-grid{grid-template-columns:1.5fr 1fr}}'''

def money(v): return 'R$ '+f'{v:,.2f}'.replace(',','X').replace('.',',').replace('X','.')
def num(v,d=0): return f'{v:,.{d}f}'.replace(',','X').replace('.',',').replace('X','.')
def perc(v): return f'{v:.2f}%'.replace('.',',')
logo='data:image/png;base64,'+base64.b64encode(LOGO.read_bytes()).decode()
cliente='MERCANTIL NOVA ERA LTDA'
uc='01374052'
ref='06/2026'
venc='21/07/2026'
cons_p=6901; cons_fp=72330; cons=cons_p+cons_fp
valor_total=76295.48; valor_p=18557.99; valor_fp=45275.83; valor_dem=12315.42; valor_reat=89.61; cosip=56.63; band=1491.05
contr=500; reg_p=151; reg_fp=167; reg=max(reg_p,reg_fp); util=reg/contr*100
custo_total=valor_total/cons; custo_ef=(valor_p+valor_fp+valor_dem)/cons
p_p=cons_p/cons*100; p_fp=cons_fp/cons*100
vp=valor_p/valor_total*100; vfp=valor_fp/valor_total*100; vdem=valor_dem/valor_total*100; vreat=valor_reat/valor_total*100
ideal=180; red=contr-ideal; econ_dem_m=7091.20; econ_dem_a=econ_dem_m*12
spread=2.689175-0.625962; econ_bess_m=cons_p*spread; econ_bess_a=econ_bess_m*12
units_energy=math.ceil((cons_p/30)/241); units_power=math.ceil(reg/108); units=max(units_energy,units_power); capex=units*550000
payback=capex/econ_bess_a
cash=[econ_bess_a*(1.04**(y-1)) for y in range(1,21)]
npv=-capex+sum(cf/(1.05**i) for i,cf in enumerate(cash,1))
lo,hi=-.9,1
for _ in range(120):
    mid=(lo+hi)/2
    val=-capex+sum(cf/((1+mid)**i) for i,cf in enumerate(cash,1))
    if val>0: lo=mid
    else: hi=mid
irr=(lo+hi)/2
cum=-capex; dpb=None
for i,cf in enumerate(cash,1):
    prev=cum; disc=cf/(1.05**i); cum+=disc
    if dpb is None and cum>=0: dpb=i-1+(-prev)/disc
fatura_bess=valor_total-econ_bess_m; reducao=econ_bess_m/valor_total*100
# SVGs
bar1=f'''<svg class="chart-svg" viewBox="0 0 480 230"><line x1="40" y1="180" x2="455" y2="180" stroke="#d9e7e1"/><line x1="40" y1="25" x2="40" y2="180" stroke="#d9e7e1"/><rect x="90" y="{180-150:.1f}" width="58" height="150" rx="8" fill="#2563eb"/><text x="119" y="22" text-anchor="middle" class="value">{num(cons_fp)} Fora ponta</text><rect x="220" y="{180-(cons_p/cons_fp*150):.1f}" width="58" height="{cons_p/cons_fp*150:.1f}" rx="8" fill="#f59e0b"/><text x="249" y="{180-(cons_p/cons_fp*150)-8:.1f}" text-anchor="middle" class="value">{num(cons_p)} Ponta</text><rect x="350" y="{180-(reg/cons_fp*150*100):.1f}" width="58" height="{reg/cons_fp*150*100:.1f}" rx="8" fill="#7c3aed"/><text x="379" y="164" text-anchor="middle" class="value">{num(reg)} kW</text><text x="90" y="205" class="axis">Fora ponta {perc(p_fp)}</text><text x="220" y="205" class="axis">Ponta {perc(p_p)}</text><text x="350" y="205" class="axis">Demanda</text></svg>'''
vals=[('Fora ponta',valor_fp,vfp,'#2563eb'),('Ponta',valor_p,vp,'#f59e0b'),('Demanda',valor_dem,vdem,'#7c3aed'),('Reativo',valor_reat,vreat,'#dc2626')]
maxv=max(x[1] for x in vals); bars=''
for i,(n,v,p,c) in enumerate(vals):
    h=150*v/maxv; x=55+i*95; y=180-h
    bars+=f'<rect x="{x}" y="{y:.1f}" width="45" height="{h:.1f}" rx="6" fill="{c}"/><text x="{x+22}" y="{y-7:.1f}" text-anchor="middle" class="value">{money(v)}</text><text x="{x+22}" y="204" text-anchor="middle" class="axis">{n} {perc(p)}</text>'
bar2=f'<svg class="chart-svg" viewBox="0 0 480 230"><line x1="40" y1="180" x2="455" y2="180" stroke="#d9e7e1"/><line x1="40" y1="25" x2="40" y2="180" stroke="#d9e7e1"/>{bars}</svg>'
# pie style
start=0; conic=[]
for n,v,p,c in vals:
    conic.append(f'{c} {start:.2f}% {start+p:.2f}%'); start+=p
pie='conic-gradient('+','.join(conic)+')'
legend=''.join(f'<li><b style="background:{c}"></b>{n}<strong>{perc(p)}</strong></li>' for n,v,p,c in vals)
# bess compare
maxc=valor_total
compare=f'''<svg class="chart-svg" viewBox="0 0 480 230"><line x1="40" y1="180" x2="455" y2="180" stroke="#d9e7e1"/><line x1="40" y1="25" x2="40" y2="180" stroke="#d9e7e1"/><rect x="80" y="30" width="70" height="150" rx="8" fill="#0f5740"/><text x="115" y="22" text-anchor="middle" class="value">{money(valor_total)}</text><text x="115" y="205" text-anchor="middle" class="axis">Atual 100,00%</text><rect x="210" y="{180-(fatura_bess/maxc*150):.1f}" width="70" height="{fatura_bess/maxc*150:.1f}" rx="8" fill="#1faa7e"/><text x="245" y="{180-(fatura_bess/maxc*150)-8:.1f}" text-anchor="middle" class="value">{money(fatura_bess)}</text><text x="245" y="205" text-anchor="middle" class="axis">Com BESS {perc(fatura_bess/valor_total*100)}</text><rect x="340" y="{180-(econ_bess_m/maxc*150):.1f}" width="70" height="{econ_bess_m/maxc*150:.1f}" rx="8" fill="#f59e0b"/><text x="375" y="{180-(econ_bess_m/maxc*150)-8:.1f}" text-anchor="middle" class="value">{money(econ_bess_m)}</text><text x="375" y="205" text-anchor="middle" class="axis">Economia {perc(reducao)}</text></svg>'''
# cash chart
maxcf=max(cash); pts=[]
for i,cf in enumerate(cash,1):
    x=45+(i-1)*(620/19); y=255-(cf/maxcf)*195; pts.append((x,y,cf))
poly=' '.join(f'{x:.1f},{y:.1f}' for x,y,_ in pts)
cf_svg=f'<svg class="chart-svg" viewBox="0 0 720 300"><line x1="40" y1="255" x2="690" y2="255" stroke="#d9e7e1"/><line x1="40" y1="35" x2="40" y2="255" stroke="#d9e7e1"/><polyline points="{poly}" fill="none" stroke="#1faa7e" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><text x="40" y="285" class="axis">1</text><text x="650" y="285" class="axis">20</text><text x="44" y="28" class="axis">Eixo Y: valor (R$) • Eixo X: tempo (anos)</text></svg>'
year_rows=''.join(f'<tr><td>Ano {i}</td><td>{money(cf)}</td></tr>' for i,cf in enumerate(cash,1))
html=f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Relatório de Auditoria Energética — Jardim Floresta | Plugga</title><style>{style}</style></head><body><main class="page"><section class="hero"><div class="eyebrow">PLUGGA GESTÃO • AUDITORIA ENERGÉTICA</div><h1>Relatório de Auditoria Energética</h1><div class="client">Cliente <b>{cliente}</b> • UC {uc} • Roraima Energia S.A. • Referência {ref} • Base de análise: fatura cativa e oportunidades energéticas</div><div class="brandmark"><img class="logo-img" src="{logo}" alt="Plugga"><div class="tag">você no controle da sua energia</div></div><div class="chips"><span class="chip">Grupo A</span><span class="chip">A4</span><span class="chip">Modalidade Verde</span><span class="chip">Prévia com 1 fatura</span></div></section><div class="toc"><span>Resumo</span><span>Identificação</span><span>Demanda</span><span>Consumo</span><span>Composição</span><span>Diagnóstico</span><span>Oportunidades</span><span>Próximos passos</span></div>
<h2>1. Resumo executivo da fatura</h2><div class="grid"><div class="kpi"><span>Valor total</span><strong>{money(valor_total)}</strong></div><div class="kpi"><span>Mês / vencimento</span><strong>{ref}</strong><small>{venc}</small></div><div class="kpi"><span>Consumo total</span><strong>{num(cons)} kWh</strong></div><div class="kpi"><span>Custo médio total</span><strong>{money(custo_total)}/kWh</strong></div></div><div class="note">Destaques: demanda contratada com utilização baixa no mês ({perc(util)}), sem ultrapassagem identificada; cobrança reativa baixa ({perc(vreat)} da fatura); a ponta custa 4,3x a fora ponta e abre oportunidade para BESS/Solar+BESS. Como há apenas uma fatura, demanda ideal e BESS ficam como prévia técnica.</div><div class="warn"><b>Atenção:</b> a fatura apresenta linha “Adicional Bandeira Amarela” de {money(band)}, mas o total a pagar fecha sem somar esse item e o campo de bandeira informa Verde. Validar NF3e/portal antes de qualquer contestação.</div>
<h2>2. Identificação da unidade consumidora</h2><table><tr><th>Campo</th><th>Informação</th></tr><tr><td>Consumidor</td><td>{cliente}</td></tr><tr><td>Unidade consumidora</td><td>{uc}</td></tr><tr><td>Concessionária/distribuidora</td><td>Roraima Energia S.A.</td></tr><tr><td>Localidade</td><td>Boa Vista/RR</td></tr><tr><td>Grupo/modalidade</td><td>Grupo A · A4 · Modalidade Verde</td></tr><tr><td>Classe/subclasse</td><td>Comercial / comercial</td></tr><tr><td>Período de consumo</td><td>31/05/2026 a 30/06/2026</td></tr><tr><td>Referência/vencimento</td><td>{ref} · {venc}</td></tr></table>
<h2>3. Análise de demanda</h2><div class="grid"><div class="kpi"><span>Demanda contratada</span><strong>{num(contr)} kW</strong></div><div class="kpi"><span>Maior demanda registrada</span><strong>{num(reg)} kW</strong></div><div class="kpi"><span>Utilização do contrato</span><strong>{perc(util)}</strong></div><div class="kpi"><span>Ultrapassagem</span><strong>Não identificada</strong></div></div><table><tr><th>Indicador</th><th>Ponta</th><th>Fora ponta</th><th>Leitura</th></tr><tr><td>Demanda contratada</td><td>0 kW</td><td>{num(contr)} kW</td><td>Contrato com folga relevante neste mês.</td></tr><tr><td>Demanda registrada</td><td>{num(reg_p)} kW</td><td>{num(reg_fp)} kW</td><td>Fora ponta foi a maior demanda registrada.</td></tr><tr><td>Demanda de referência para análise de potência</td><td>{num(reg_p)} kW</td><td>{num(reg_fp)} kW</td><td>Usada para avaliar potência necessária em cenário BESS.</td></tr><tr><td>Utilização</td><td>—</td><td>{perc(util)}</td><td>Há indício de contrato acima da necessidade, sujeito a histórico.</td></tr><tr><td>Tolerância de ultrapassagem</td><td>Até 5% acima do contrato</td><td>Até 5% acima do contrato</td><td>Sem ultrapassagem identificada.</td></tr></table><div class="demand-box"><div class="demand-head"><span>Prévia de demanda ideal</span><strong>{num(ideal)} kW</strong></div><div class="demand-grid"><div><span>Contrato atual</span><b>{num(contr)} kW</b></div><div><span>Maior demanda registrada</span><b>{num(reg)} kW</b></div><div><span>Limite sem ultrapassagem</span><b>{num(ideal*1.05,1)} kW</b></div><div><span>Redução preliminar</span><b>{num(red)} kW ({perc(red/contr*100)})</b></div><div><span>Economia estimada mensal</span><b>{money(econ_dem_m)}</b></div><div><span>Economia estimada anual</span><b>{money(econ_dem_a)}</b></div></div><p>Com base apenas nesta fatura, a demanda contratada pode ter espaço para ajuste preliminar para {num(ideal)} kW, mantendo margem regulatória sobre o maior registro observado no mês. Esta recomendação ainda depende de 12 faturas e memória de massa antes de qualquer solicitação formal à distribuidora.</p></div>
<h2>4. Consumo, custo médio efetivo e tarifa aplicada</h2><div class="grid"><div class="kpi"><span>Consumo ponta</span><strong>{num(cons_p)} kWh</strong><small>{perc(p_p)} do consumo</small></div><div class="kpi"><span>Consumo fora ponta</span><strong>{num(cons_fp)} kWh</strong></div><div class="kpi"><span>Custo energia efetivo</span><strong>{money(custo_ef)}/kWh</strong></div><div class="kpi"><span>Custo médio total</span><strong>{money(custo_total)}/kWh</strong></div></div><div class="note">Leitura: o custo médio de energia efetivo considera energia e demanda. O custo médio total considera todos os componentes da fatura. Essa separação mostra quanto custa usar energia e quanto custa a fatura completa.</div><table><tr><th>Posto/componente</th><th>Consumo/base</th><th>Tarifa aplicada</th><th>Valor faturado</th><th>Peso no total</th></tr><tr><td>Energia ponta</td><td>{num(cons_p)} kWh</td><td>R$ 2,689175/kWh</td><td>{money(valor_p)}</td><td>{perc(vp)}</td></tr><tr><td>Energia fora ponta</td><td>{num(cons_fp)} kWh</td><td>R$ 0,625962/kWh</td><td>{money(valor_fp)}</td><td>{perc(vfp)}</td></tr><tr><td>Demanda</td><td>514 kW faturados</td><td>Conforme fatura</td><td>{money(valor_dem)}</td><td>{perc(vdem)}</td></tr></table>
<h2>5. Composição da fatura, reativo e benefício fiscal</h2><div class="grid"><div class="kpi"><span>Energia reativa</span><strong>{money(valor_reat)}</strong><small>{perc(vreat)} da fatura</small></div><div class="kpi"><span>Bandeira</span><strong>Validar</strong></div><div class="kpi"><span>Multa/juros/encargos</span><strong>{money(0)}</strong></div><div class="kpi"><span>Benefício/isenção</span><strong>A validar</strong></div></div><table><tr><th>Item</th><th>Valor</th><th>Peso no total</th><th>Leitura</th></tr><tr><td>Reativo ponta</td><td>{money(3.44)}</td><td>{perc(3.44/valor_total*100)}</td><td>Baixo impacto isolado.</td></tr><tr><td>Reativo fora ponta</td><td>{money(86.17)}</td><td>{perc(86.17/valor_total*100)}</td><td>Maior parte da cobrança reativa.</td></tr><tr><td>Total reativo</td><td>{money(valor_reat)}</td><td>{perc(vreat)}</td><td>Monitorar; não é a principal dor neste mês.</td></tr><tr><td>Benefício/isenção fiscal</td><td>A validar</td><td>A validar</td><td>ICMS informado: R$ 13.709,86. PIS/Cofins zerados na fatura.</td></tr></table><div class="chart-pair"><div class="mini-chart"><h3>Consumo e demanda</h3>{bar1}</div><div class="mini-chart"><h3>Composição econômica</h3>{bar2}</div></div><div class="chart-pair"><div class="mini-chart"><h3>Participação por componente</h3><div class="pie-wrap"><div class="pie" style="background:{pie}"></div><ul class="pie-legend">{legend}</ul></div></div><div class="mini-chart"><h3>Comentários</h3><p>A energia fora ponta concentra a maior parte do valor, mas a ponta representa custo desproporcional: somente {perc(p_p)} do consumo e {perc(vp)} do valor total da fatura. Isso explica por que a oportunidade está no deslocamento/gestão do custo de ponta e também na revisão segura da demanda contratada.</p></div></div>
<h2>6. Diagnóstico e recomendações da auditoria</h2><div class="note">Demanda: indício de contrato acima do uso neste mês, sem ultrapassagem. Reativo: cobrança existe, mas com peso muito baixo. Benefício fiscal: base tributária deve ser conferida para proteger eventual vantagem tributária. Tarifa/regulação: validar tarifa homologada e NF3e antes de transformar esta análise em documento de contestação ou proposta. Oportunidade principal: demanda sem investimento e gestão do custo de ponta.</div>
<h2>7. Oportunidades</h2><div class="note">A auditoria indica fatura com baixa utilização de demanda e custo de ponta muito superior ao fora ponta. Isso abre espaço para estudar soluções como BESS, Solar+BESS e Mercado Livre de energia.</div><div class="grid"><div class="kpi"><span>Economia estimada mensal</span><strong>{money(econ_bess_m)}</strong></div><div class="kpi"><span>Economia Ano 1</span><strong>{money(econ_bess_a)}</strong></div><div class="kpi"><span>Fatura com BESS estimada</span><strong>{money(fatura_bess)}</strong></div><div class="kpi"><span>Redução estimada</span><strong>{perc(reducao)}</strong></div></div><div class="chart-pair"><div class="mini-chart"><h3>Fatura atual x BESS</h3>{compare}</div><div class="mini-chart"><h3>Pré-dimensionamento BESS</h3><div class="dim" style="margin:0;grid-template-columns:repeat(2,1fr)"><div class="box"><b>{num(cons_p/30,0)}</b><br><span>kWh ponta/dia</span></div><div class="box"><b>{units_energy}</b><br><span>por energia</span></div><div class="box"><b>{units_power}</b><br><span>por potência</span></div><div class="box"><b>{units}</b><br><span>preliminar</span></div></div></div></div><table class="scenario-table"><tr><th>Cenário</th><th>CAPEX estimado</th><th>Economia Ano 1</th><th>Payback</th><th>Leitura executiva</th></tr><tr><td>Sem investimento</td><td>{money(0)}</td><td>{money(econ_dem_a)}</td><td>A definir</td><td>Validar redução de demanda, rotina financeira e conferência regulatória.</td></tr><tr><td>Apenas BESS — referência</td><td>{money(capex)}</td><td>{money(econ_bess_a)}</td><td>{num(payback,1)} anos</td><td>{units} unidades LUNA2000-241. VPL {money(npv)}; TIR {perc(irr*100)} em 20 anos.</td></tr><tr><td>Solar + BESS</td><td>A dimensionar</td><td>A simular</td><td>A simular</td><td>Exige área disponível, curva horária e geração estimada.</td></tr><tr><td>Mercado Livre</td><td>Baixo CAPEX</td><td>A simular</td><td>—</td><td>Exige preço de mesa e análise de elegibilidade.</td></tr></table><div class="grid3"><div class="kpi"><span>VPL com TMA</span><strong>{money(npv)}</strong></div><div class="kpi"><span>TIR</span><strong>{perc(irr*100)}</strong></div><div class="kpi"><span>Payback descontado</span><strong>{num(dpb,1)} anos</strong></div></div><div class="note">Premissas da pré-viabilidade: horizonte de 20 anos, reajuste tarifário de 4% ao ano, TMA de 5% ao ano, economia estimada a partir do consumo de ponta identificado na fatura e CAPEX de referência de R$ 550 mil por BESS. A decisão de investimento depende de 12 faturas, memória de massa, cotação EPC e validação regulatória.</div><div class="flow-grid"><div class="mini-chart"><h3>Economia anual projetada</h3>{cf_svg}</div><div class="mini-chart"><h3>Fluxo de caixa acumulado</h3><table style="width:100%;margin:0"><tr><th>Período</th><th>Valor</th></tr>{year_rows}</table></div></div>
<div class="analysis"><div class="eyebrow">ANÁLISE TÉCNICA</div><h2>Análise de eficiência energética</h2><p>A fatura de energia da unidade Jardim Floresta apresenta baixa utilização da demanda contratada nesta referência e não demonstra dor de ultrapassagem. A cobrança de reativo aparece em patamar muito baixo, recomendando monitoramento técnico sem prioridade imediata de investimento.</p><p>O ponto de maior atenção está no custo de ponta e na possível folga contratual. Embora a ponta represente apenas {perc(p_p)} do consumo físico, ela responde por {perc(vp)} do valor total da fatura. A diferença entre ponta e fora ponta cria oportunidade para estudo de deslocamento de carga, BESS, Solar+BESS e Mercado Livre.</p><p>A pré-viabilidade com BESS indica economia estimada de {money(econ_bess_m)}/mês e {money(econ_bess_a)} no primeiro ano, considerando o cenário de referência. O dimensionamento preliminar aponta {units} unidades LUNA2000-241, limitado por potência, não apenas por energia.</p><p><b>Recomendação Plugga:</b> avançar para validação com 12 faturas, memória de massa em 15 minutos, confirmação tarifária/regulatória e cotação EPC fechada antes de transformar esta oportunidade em proposta comercial.</p></div>
<h2>8. Próximos passos</h2><div class="timeline"><div class="step"><div class="num">1</div><h3>Enviar histórico</h3><p>Reunir 12 faturas para confirmar sazonalidade, demanda e consumo em ponta.</p></div><div class="step"><div class="num">2</div><h3>Memória de massa</h3><p>Enviar memória de massa em 15 minutos para validar potência real, duração da ponta e cargas críticas.</p></div><div class="step"><div class="num">3</div><h3>Validar bases</h3><p>Confirmar tarifa homologada, regra tributária, bandeira/NF3e e benefício fiscal aplicável.</p></div><div class="step"><div class="num">4</div><h3>Simular cenários</h3><p>Simular BESS, Solar+BESS e Mercado Livre com dados completos.</p></div><div class="step"><div class="num">5</div><h3>Obter cotações</h3><p>Obter cotações para projeto básico, projeto executivo, EPC, operação e manutenção.</p></div></div><div class="footer"><img src="{logo}" alt="Plugga"><strong>você no controle da sua energia</strong> • contato@plugga.app.br</div></main></body></html>'''
OUT.write_text(html,encoding='utf-8')
print(OUT)
print('units', units, 'capex', money(capex), 'npv', money(npv), 'irr', perc(irr*100))
